### ISSUE TITLE
Get it running on debian

### ISSUE THREAD

**Issue by KueWW** [thawn/ttmp32gme#12]
Hello there,

I'm afraid but I can't get _ttmp32gme_ running on a _debian_ system.
I tried to run the cpan command. But there are a couple of errors.

Can you give more detailed help?

Thanks in advance.

**Comment by thawn** [comment]
Hi,

could you please post the complete command line output after you try to 
start ttmp32gme?

Thanks.

**Comment by KueWW** [comment]
Hi,
I'm not an expert in using _debian_ console commands an all that stuff.
I understood the installing description to the following command:

cpan -i EV AnyEvent::HTTPD Path::Class Cwd File::Basename File::Find List::MoreUtils PAR Encode Text::Template; JSON::XS; URI::Escape; Getopt::Long; Perl::Version; DBI; DBIx::MultiStatementDo; Log::Message::Simple Music::Tag::MP3 Music::Tag::OGG Music::Tag::MusicBrainz Music::Tag::Auto MP3::Tag Image::Info

But i have no idea what it does. After running the command it happens a lot at teh console. The screenshot inthe at tachement shows the last results.....

![bildschirmfoto von 2017-08-04 12-59-01](https://user-images.githubusercontent.com/7642828/28966278-98b46530-7915-11e7-8eed-fea79e0f2bb3.png)

**Comment by KueWW** [comment]
Hi,
excuse my late reply.
Now the build was successfully. Thanks a lot.

You're right. My debian is running on a _virtual box_. The windows version of _ttmp32gme_ is runnig well on windows. Except the printer. Sometimes the _tiptoi_ pen is able to red sometimes not....
But that's another issue. I'm trying to setup a alternative system to windows. Actally I#m chekcing out if all the tools I'm using are able to run on debian......

A last question to this issue. Now that _ttmp32gme_ was compiled how can I start / use it.
I can't see.

Thanks in advance.....

**Comment by thawn** [comment]
> A last question to this issue. Now that ttmp32gme was compiled how can I start / use it.

Sorry, I missed that last question.
Actually, on debian, the program is not supposed to be built at all.
try the following commands:
`cd ttmp32gme/src
perl ttmp32gme.pl`

then open a browser and enter the following url:
http://127.0.0.1:10020/

I hope this helps...

**Comment by thawn** [comment]
Closing this for now. Please reopen if you still have issues.

**Comment by thawn** [comment]
We now have [a docker image](https://hub.docker.com/r/thawn/ttmp32gme).

**Comment by KueWW** [comment]
I've tried it!
Brilliant! Thank you very, very much for that!

**Comment by thawn** [comment]
@KueWW excellent :-). Thanks for the feedback!
