### ISSUE TITLE
No Print possible

### ISSUE THREAD

**Issue by Heroidas** [thawn/ttmp32gme#13]
Hej there, i tried to push the "print" button, but nothing happend.
I tried it in Safari, Firefox and Chrome aswell.

This is the Error-Code I got:

/var/folders/w8/kl5hx_pd0h9ccq3d85_75wch0000gn/T/par-6d617276696e77616c746572/cache-b5eed44f8e0afcbe05efc266dc4e935dbdaa8c3a/inc/lib/tttool --dpi 1200 --pixel-size 2  --code-dim 24 oid-code 924
tttool: oid-924.png: openBinaryFile: permission denied (Read-only file system)
[ERROR] Writing oid-924.png.. (Code 924, raw code 14141)

unhandled callback exception on event (/print, AnyEvent::HTTPD=HASH(0x7fcb61acc570), AnyEvent::HTTPD::Request=HASH(0x7fcb5e9b0178)): Could not create oid file:  at TTMp32Gme/TttoolHandler.pm line 277.

Is there an easy way to fix this problem?
Sorry, but im just a father who want to print some codes for the animal of my son and have
no, really no programming skills.
I would be really glad for your help.

Thx for starting this awesome project and keep on making great stuff like this!!!

**Comment by thawn** [comment]
Have you tried just printing from the browser? This should work on a mac 
and also from firefox on linux.

**Comment by Heroidas** [comment]
I work on Mac. The hole program Works inside the browser. I cant Print from the browser, because there appeare no codes. I push the green Print Button and nothing Else happens.

**Comment by thawn** [comment]
It seems that there is a problem with write permissions. Could you 
please tell me if the folder "~/Library/Application Support/ttmp32gme" 
exists and is writable and what it contains (it should contain a file 
config.sqlite, a folder library and a folder oid_cache).

To open the library, in Finder Alt-click on "go -> Library"

If something is wrong with that folder, try renaming it and start 
ttmp32gme again.

**Comment by Heroidas** [comment]
It didn't exist.
I created it an put all the files in it.
It works now on Safari! Thx a lot!!!

Thats Awesome!

**Comment by thawn** [comment]
Glad it works now. I'll look into what may cause the folder to not be 
created on mac systems.
