### ISSUE TITLE
Necessary packages on Linux Mint 18.3 (based ubuntu 16.04)

### ISSUE THREAD

**Issue by coldhand7** [thawn/ttmp32gme#15]
Hello @thawn,
thanks for your great work. I successfully started the ttmp3gme perl script on Linux Mint 18.3 (based on ubuntu 16.04). I had to add the following linux packages to be able to install the necessary modules using cpan:
`sudo apt-get install libc6-dev libxml2-dev zlib1g-dev`

Could you please add this hint in your README.md? Thanks.

Despite I executed the following command I had to install some modules manually again:
`sudo cpan -i EV AnyEvent::HTTPD Path::Class Cwd File::Basename File::Find List::MoreUtils PAR Encode Text::Template JSON::XS URI::Escape Getopt::Long Perl::Version DBI DBIx::MultiStatementDo Log::Message::Simple Music::Tag::MP3 Music::Tag::OGG Music::Tag::MusicBrainz Music::Tag::Auto MP3::Tag Image::Info`

Keep up your good work!

**Comment by thawn** [comment]
Thank you very much for the valuable feedback!. I updated the documentation accordingly.

**Comment by Dupplicate** [comment]
also needed: WebService::MusicBrainz::Artist

**Comment by thawn** [comment]
We now have [a docker image](https://hub.docker.com/r/thawn/ttmp32gme)
