### ISSUE TITLE
Titel Stopp nach jedem Song

### ISSUE THREAD

**Issue by donms62** [thawn/ttmp32gme#18]
Hi, ich habe ein Bilderbuch erstellt, in mehreren Kategorien, also max 8 mp3 Stücke pro gme Datei.

Nun habe ich das Problem, dass beim Startbutton der erste Titel abgespielt wird. Das ist auch ok. Aber der Stift "stoppt nicht", sondern spielt die weiteren Stücke nacheinander ab, OHNE dass ich auf den dazugehörigen Code klicken muss. 

MP3 Tags sind alle korrekt eingetragen.

Wie kann ich das einstellen?

Nutze ttmp32gme  0.2.2 - habe aber auch die vorherigen Versionen ausprobiert.

Was mache ich falsch?
DANKEEEEEEEEEE!

**Comment by thawn** [comment]
It's not a bug, it's a feature ;-)
Im Ernst: ttmp32gme ist eigentlich dafür gedacht, Hörspiele und musik auf den tiptoi zu bringen. Da ist es gewünscht, dass der Tiptoi weiter spielt (wie ein mp3/cd player).

ttmp32gme wird auch nie ein Bilderbucheditor werden. Das ist viel zu kompliziert da alle Anwendungsfälle abzudecken, dafür fehlt mir die Zeit das zu implementieren.

Für Bücher wird bis auf Weiteres tttool das Mittel der Wahl bleiben.

Ein Hack wäre, nur einen Song in jedes Album zu packen. Dann wird dieser Song mit dem Anschaltzeichen abgespielt und danach gestoppt.

Was Du auch machen kannst, ist die yaml-Datei mit einem Texteditor zu ändern und tttool von der Kommandozeile zu starten. Die von Hand erstellte gme Datei sollte dann auch mit den Ausdrucken von ttmp32gme funktionieren. Falls Du das machen möchtest, sag' Bescheid, dann versuche ich Dir Starthilfe zu geben.

**Comment by donms62** [comment]
Hallo, und Vielen Dank!
Ich denke, ich werde für jeden Song einen Startbutton generieren lassen. 
Das Problem bei den Alben ist, dass die StartID IMMER 920 ist, es sei denn ich habe mehrere Dateien in der Libery (lässt sich zwar ändern, aber ttmp32gme schreibt immer 920 in die yaml. Die habe ich dann extraiert und geändert, war ein bisschen Fummelei - vor allem die yaml dann wieder in die gme schreiben hat nicht so auf Anhieb funktioniert. Danke nochmal, wenn ich Hilfe brauche werde ich mich melden... :-D

**Comment by thawn** [comment]
> Das Problem bei den Alben ist, dass die StartID IMMER 920

Das erste Album bekommt immer die OID 920. Danach bekommt aber jedes weitere Album eine neue OID. Hast Du nach dem Erstellen der gme Datei das Album jedes mal wieder gelöscht?
Im Prinzip kannst Du doch die mp3 Dateien über die Upload Seite einzeln hochladen (eine Datei hochladen -> "add album to library" anklicken -> nächste Datei hochladen -> "add album to library" anklicken etc. pp...). Dann hast Du alle Dateien in eigenen Alben und kannst sie separat zum Drucken auswählen. Dabei sollte es keine Überschneidung der OIDs geben.

**Comment by donms62** [comment]
Hallo! Danke für die Antwort! Ja, ich hatte - weil alles nicht so funktionierte, den Temp Ordner und den tttgme Ordner LEER gemacht, daher hat dann das Programm immer die gleiche OID generiert. Die konnte ich auch nicht ändern! Aber danach ging es, nachdem ich die Anleitung auf der tttool Seite gelesen hatte - nach einigen VErsuchen klappte es dann: Wichtig (aus Fehlern lernt man ja :-D) eindeutige Tags in den mp3s (ansonsten überschreibt das Programm die "unknown.gme" gnadenlos ... ) UND den Temp Ordner nicht leeren - dann bekommt jedes weitere Album die OID 920+1x. Mittlerweile bin ich bei OID 987, da ich jede Datei einzelnd generieren lasse und nun für jedes Stück einen Startbutton habe. WENN ich mehrere Dateien in ein Album packe, nehme ich eine eigene mp3 auf (zB eine Anleitung) und füge am Ende "Stille" ein, damit nicht sofort das 2. Stück gespielt wird. Somit hat das Kind Zeit, ein anderes Stück zu wählen.....DANKE für die HILFE! :-D

**Comment by thawn** [comment]
Super, freut mich dass es jetzt geht :)

> Mittlerweile bin ich bei OID 987

wundere Dich nicht, wenn nach 999 dann 919, 918... kommt. 999 ist in der Ravensburger Definition die maximal mögliche start OID. ttmp32gme fängt bei 920 an, da Ravensburger für seine Produkte bei 1 Anfing zu zählen - so ist die Wahrscheinlichkeit gering, dass die selbstgemachten gme Dateien sich mit Ravensburger gme Dateien überschneiden.

Ich bin mal gespannt was Ravensburger macht wenn sie selbst irgendwann mehr als 999 Tiptoi Produkte haben... Beim Design hat Ravensburger wohl selbst nicht damit gerechnet, dass der Tiptoi so ein Erfolg wird. Das erinnert mich irgendwie an MSDOS: Bill Gates hat beim Programmieren von DOS auch nicht damit gerechnet dass Computer jemals mehr als 640 kB (ja richtig Kilobyte!) Arbeitsspeicher haben werden ;-).

**Comment by donms62** [comment]
Haha, ja, die Probleme mit DOS kenne ich, wir wurden ja zur Sparsamkeit erzogen. Wenn man dann nicht händisch oder in der config.sys in den obere Speicherbereich geladen hat, gab es dann später den "memmaker", der das regelte und man für bestimmte Spiele 678kb frei hatte....oder so..... :-D

**Comment by JakeHubson** [comment]
Wie kommt man denn an die yaml Datei wie oben beschrieben? Für tttool find ich nur assemble... Gibt es auch disassemle? :)
Und weißt du was geändert werden muss damit das automatische abspielen des nächsten Titels verhindert wird?

**Comment by thawn** [comment]
der tttool befehl zum Erzeugen einer yaml-Datei lautet: `tttool export album.gme`
ttmp32gme erzeugt aber auch schon eine yaml Datei, die Du ändern kannst. Die yaml Dateien findest Du in dem versteckten Ordner: `<Benutzerordner>\AppData\ttmp32gme\library\<albumname>`
in der Yaml Datei ersetzt Du dann alle `J(<zahl>)` Befehle durch `C`

**Comment by JakeHubson** [comment]
funktioniert einwandfrei. Vielen Dank!

**Comment by thawn** [comment]
Freut mich, viel Spass Dir und Deinem Kind ;-)
