### ISSUE TITLE
Ausdruck

### ISSUE THREAD

**Issue by digi-thomas2003** [thawn/ttmp32gme#2]
Hallo Till,

zunächst: Klasse Arbeit, die Du hier machst!
Allerdings habe ich mit dem Ausdruck ein Problem: Der Tiptoi will bei mir einfach die OIDs nicht erkennen.
Verwendete Hard- + Software: Brother 9022CDW mit 600 dpi, Win 7, Firefox aktuelleste Version
Erstelle ich beispielsweise mit Andis ttaudio einen Ausdruck, liest mein Stift die OID problemlos, ohne besondere Einstellungen am Drucker.
Ich habe mit Deinem tool mit den Auflösungen 1200 und 600 dpi und mit 1 und 2 pix alle Kombinationen erfolglos getestet.
Ich habe da Gefühl (ist aber echt nur ein Gefühl), dass die Skalierung der OIDs bei Dir nicht korrekt ist. Kannst Du das bitte nochmals prüfen?
Mich irritiert halt total, das mit Andis Tool das Erkennen der gedruckten OIDs auf Anhieb funzt und ich es mit Deinem Tool einfach nicht hinkriege.
Kannst Du mir hier vielleicht noch einen Tipp geben?
Vielen Dank!!

Herzliche Grüße
Thomas

**Comment by thawn** [comment]
Hallo Thmoas,

Du hast recht, das liegt vermutlich an der Skalierung der OIDs. Bei mir 
auf meinem Rechner und in der virtuellen maschine unter windows 10 hat 
es mit Chrome (und auch mit Firefox) funktioniert.

Welchen Browser verwendest Du?

Kannst Du bitte mal die Seite in ein pdf drucken und mir zuschicken?

Hier ein paar Hintergründe:

Andi und ich verwenden verschiedene Bildformate (er SVG, ich png) und 
verschiedene Seitenlayouts. Das es mit Andis Tool funktioniert heißt 
also nur, dass dein Drucker prinzipiell die OIDs ausdrucken kann (was ja 
schonmal ne wichtige Info ist :)

Du kannst Dir die ausgedruckten Anschaltzeichen ja auch mal ganz genau 
anschauen (z.B. mit einer Lupe) da sollten jede Menge Punkte zu sehen 
sein, die gut voneinander abgegrenzt sind und alle 4 Zeilen ein ganz 
regelmäßiges Muster haben. Siehe hier:

https://github.com/entropia/tip-toi-reveng/blob/master/docs/The_Code.pdf

LG

Till

**Comment by thawn** [comment]
p.s. bei mir funktioniert mit einem Brother MFC-L2700DW bei 1200 dpi die 
Einstellung 1200 dpi und 3 pix am besten.

LG

Till

**Comment by thawn** [comment]
Hallo,

Ich habe jetzt das Drucken auch unter Windows etwas ausführlicher getestet. Die Ergebnisse waren leider eher durchwachsen. Genauso gut wie auf meinem Mac hat es unter Windows 10 nur mit Microsoft Edge funktioniert (--dpi 1200 --pixel-size 2). Mit Opera ausgedruckt haben die OIDs nur manchmal funktioniert und mit Chrome und Firefox gar nicht. Aus irgendwelchen Gründen rastern die Browser (außer Edge) die PNG Bilder beim Drucken mit sehr niedriger Auflösung (~300-600ppi).

@Andreas ich schätze, Deine Lösung mit den SVG Bildern funktioniert unter Windows doch deutlich besser. Man muss halt Firefox zum ausdrucken nehmen. Die Beschränkung auf Edge ist da doch eine stärkere Einschränkung, da der nur unter Windows 10 läuft.

Ich werde leider erst einmal nicht dazu kommen einen SVG-OID-Generator in perl oder Javascript zu schreiben. Falls jemand anderes Zeit und Lust hat, würde ich mich natürlich freuen und den code gerne integrieren ;-).

Ich habe schon rumgegoogelt und habe nirgends gefunden, wie ich die Browser dazu bringen kann die Bilder in hoher Auflösung zu drucken, bzw ohne zu Rastern an den Drucker zu schicken (auf dem Mac bzw mit Edge scheint das aber zu klappen). Falls jemand mehr weiß als ich, sagt bitte Bescheid.

Viele Grüße

Till

**Comment by thawn** [comment]
> Was vermutlich auch gut geht ist wenn ihr (so wie "ttool oid-table")
> PDFs statt HTML erzeugt.
Das hätte den Vorteil, dass wir uns nicht mit Browserkompatibilität herumschlagen müssten. Am besten wäre natürlich ein HTML->PDF Konverter. Ich habe eben [flying saucer](http://flyingsaucerproject.github.io/flyingsaucer/r8/guide/users-guide-R8.html) gefunden. Das ist bei Gelegenheit einen Versuch wert.

**Comment by thawn** [comment]
Fixed on Windows:
https://github.com/thawn/ttmp32gme/releases/tag/v0.1.0-win

**Comment by digi-thomas2003** [comment]
Hallo Till,

supi!! Mit der PDF klappt das Erkennen jetzt einwandfrei!
Danke für Deine Bemühungen!!
Nur noch eine kleine Kleinigkeit: Die Umlaute erscheinen beim Ausdruck nicht richtig. Statt ä, ö oder ü erscheint ein weißes ? in einer schwarzen Raute.

Herzliche Grüße
Thomas

**Comment by thawn** [comment]
Hallo Thomas,

Danke für die Rückmeldung!

Sind die Umlaute auch schon in der Library falsch oder nur im pdf?

LG

Till

**Comment by digi-thomas2003** [comment]
Hallo Till,

in der Library werden sie richtig angezeigt, nur im PDF nicht mehr.

Herzliche Grüße
Thomas

**Comment by thawn** [comment]
o.k. danke, ich schaue es mir mal an.

**Comment by digi-thomas2003** [comment]
Hallo Till,

die Umlaute erscheinen nun auch in der PDF korrekt.
Für mich funktioniert nun alles wie gewünscht, deswegen schließe ich hier zu.

Herzliche Grüße
Thomas

**Comment by thawn** [comment]
Hallo Thomas,
Ich mache das issue der Form halber nochmal auf, da ich die PDF generierung noch unter Mac und Linux testen möchte. Ich mache das issue dann zu, wenn ich die entsprechende Version release.
Danke für Dein Feedback!
VG
Till

**Comment by dirtyheizer** [comment]
Hallo,
vorab vielen Dank für die unmengen Zeit und Invest.
Ich versuche gerade die Funktion Save PDF unter ner VM mit WIn 10 zu nutzen.
PopUp blocker deaktiviert, dein tool schmeisst mir folgende Meldung raus, es wir keine PDF im Verzeichnis erstellt, und auch per manueller Adresse nicht zu bekommen..

CMD auszug:

`C:\Users\marcu\AppData\Local\Temp\par-6d61726375\cache-8f1304b3f7e188adb49363ef0e48ad20dae87431\inc\lib\wkhtmltopdf.exe -B 0.5in -T 0.5in -L 0.5in -R 0.5in http://localhost:10020/pdf C:\Users\marcu\AppData\Roaming\ttmp32gme\library\print.pdf
Qt: Untested Windows version 10.0 detected!
Loading page (1/2)
unhandled callback exception on event (/print.pdf, AnyEvent::HTTPD=HASH(0x86b8e90), AnyEvent::HTTPD::Request=HASH(0x8c69b88)): Can't read C:\Users\marcu\AppData\Roaming\ttmp32gme\library\print.pdf: No such file or directory at TTMp32Gme/LibraryHandler.pm line 159.`

Hast du ne Idee hierzu?
Danke für deine Hilfe.
MfG Dirtyheizer

**Comment by thawn** [comment]
@dirtyheizer es könnte schlicht sein, dass Deine VM zu langsam ist. Hast Du mal nach 1-2 min geschaut ob das PDF dann im Ordner C:\Users\marcu\AppData\Roaming\ttmp32gme\library\print.pdf liegt? (AppData ist ein versteckter Ordner, Du must im explorer erst "versteckte Dataien anzeigen" anklicken bevor Du den siehst).

Wieso verwendest Du überhaupt eine VM? unter Linux/Mac sollte der Druck direkt aus dem Browser klappen. Unter Linux habe ich positives mit Firefox gehört, unter Mac klappt es bei mir mit Chrome und Firefox.

**Comment by dirtyheizer** [comment]
so, sorry für die späte Rückmeldung.
ich habe es jetzt mit ttmp32 probiert aufm OSX 10.12.2 und selbes prozedere, ich werde morgen mal einen anderen Drucker probieren, auch die Testdruckseite des Brother HL-2030 sieht nit gut aus..melde mich..

**Comment by dirtyheizer** [comment]
so, ich habe es in der zwischenzeit auch aufm Firmen Laserdrucker probiert, das hat der TipToi auch nicht hinbekommen zu lesen, ich glaube ich mache da grundzätzlich etwas falsch..

**Comment by thawn** [comment]
Mit unserem firmenlaser klappt es bei mir auch nicht, da der nu"nur" 600 
dpi kann und da der irgendwie blöd rastert.

Hast Du mal auf dem Laser schwarzweiss Druck mit 1200 DPI versucht. In 
ttmp32gme ist bei mir 1200 dpi und 3 pixel die beste Einstellung.

Viel Erfolg.

**Comment by chbacher** [comment]
Hallo Till,

auch ich möchte mich für Dein Engagement bedanken. Nach einigem hin und her mit Perl habe ich das Tool auf Linux zum Laufen gebracht. Ich kann alle Funktionen nutzen - zum Test habe ich ein Album hochgeladen. Erfolgreich.

Doch wenn ich versuche zu drucken geht das PDF Pop-up zwar auf ABER der Browser (Chrome) lädt unendlich mit dem Hinweis "Warten auf 127.0.0.1".

Kannst Du mir ggf. hier weiterhelfen? Brauchst Du mehr Infos

Danke.

Chris

**Comment by thawn** [comment]
Unter Linux brauchst Du kein PDF zu generieren. mit Firefox kannst Du 
die Seite einfach direkt ausdrucken und das sollte funktionieren.

der Button für die PDFs ist im Moment nur unter Windows funktional. Bzw. 
müsstest Du noch wkhtmltopdf versin 0.13.0 alpha installieren.

Ich hoffe das hilft.

**Comment by thawn** [comment]
fixed in version 0.2.0

**Comment by dirtyheizer** [comment]
Hallo,

ich bestätigen, dass die Vers. 2.0.0 unter OSX 10.12.3
mit Chrome Version 56.0.2924.87 (64-bit)
und neuem Drucker Brother MFC-9332CDW mit
Einstellungen 600OID/2pxl/ 24 sauber funktioniert.

Vielen Dank für das Projekt, kann man dir nen Paypal Kaffee ausgeben?

Mfg
Marcus



-- 
Marcus Loßow
Sent with Airmail

On 17. Februar 2017 at 23:42:15, thawn (notifications@github.com) wrote:

fixed in version 0.2.0

**Comment by thawn** [comment]
Hi Marcus,
Danke für das Feedback. Kaffee ist nicht nötig, aber danke für das Angebot :-)
LG
Till
