### ISSUE TITLE
TipToi Pen not recognized by ttmp32gme

### ISSUE THREAD

**Issue by 901424** [thawn/ttmp32gme#20]
Hi! Thank you for this tool - it works great so far for one of our tiptois :-) My kids use two different tiptoi pens. The new one (with player) is being recognized by the tool without problems. The button "copy to tiptoi" comes up. If I try to use the older pen without player, the button doesn't appear. What can I do? thx

**Comment by thawn** [comment]
You can simply copy the gme files manually to the TipToi pen:
locate the ttmp32gme library: C:\Users\[username]\AppData\ttmp32gme
in there locate the gme files (of course you need to press the "create gme" button in ttmp32gme first) and copy them onto the pen.

Could you please let me know what the name of the volume of the old pen is? ttmp32gme looks for a drive that has the volume name tiptoi and if it finds such a drive, it shows the copy to tiptoi button.

**Comment by 901424** [comment]
Hi! Copying directly onto the pen works - thank you. The drive is called TIPTOI (Tiptoi ZC3201).

**Comment by thawn** [comment]
@901424 I think I fixed the issue in v0.2.3. However, I don't have an old pen to test. Could you please test and report back here?

**Comment by thawn** [comment]
Marking this issue as stale. Unless I hear back within 30 days, I am closing this issue

**Comment by thawn** [comment]
Please re-open the issue if you still have problems
