### ISSUE TITLE
Feature request: No auto skip

### ISSUE THREAD

**Issue by Superwallah** [thawn/ttmp32gme#24]
albums/GMEs generated with this tool always continue with the next audio file when the preceding has finished. Without interaction the complete album is being played.

I would like to use this tool for generating single OIDs for each sound file that can only be triggered one by one. I want them only to be played when the corresponding OID is scanned.
I could use the standard tttool for it, but using the web front-end including the print output is more convenient. 

It would be nice if configuration offered the option to switch of the automatic skip to the next audio file.
Can this be done manually?

**Comment by thawn** [comment]
This is already [on my todo list](https://github.com/thawn/ttmp32gme#todo). I moved it up from "Maybe later" to the more urgent list, but I cannot promise when I will be able to implement this feature.

In the meantime, you can do this by manually changing the `yml` file generated by ttmp32gme. You can find this file under `<your user folder>\AppData\remote\ttmp32gme\library` (in Windows), `~/Library/Application Support/ttmp32gme/library` (Mac) or `~/.ttmp32gme/library` (Linux).
In this file, you can remove all J(tXX) commands to get the behavior you want. On a mac/linux command line, you can do this with this command: `sed -i 's/J(t[0-9]*)//g' <album name>.yaml` afterwards, you can delete the gme file if it exists and re-generate it in tttmp32gme (you may need to re-start ttmp32gme after deleting the gme file to make sure that ttmp32gme realizes that it is gone.
