### ISSUE TITLE
How to reset the printing configuration to default settings?

### ISSUE THREAD

**Issue by Szandi90** [thawn/ttmp32gme#26]
Hello there!
I messed with the printing configuration and now it won't open the page anymore when I press "print". It shows me this error message:

l.exe --dpi 72 --pixel-size 2  --code-dim 24 oid-code 3945
tttool.exe: Dots too large. Try a smaller pixel size
CallStack (from HasCallStack):
  error, called at src/OidCode.hs:156:46 in main:OidCode
[ERROR] Writing oid-3945.png.. (Code 3945, raw code 53843)

unhandled callback exception on event (/print, AnyEvent::HTTPD=HASH(0x9325ef0), AnyEvent::HTTPD::Request=HASH(0x96f3d58)): Could not create oid file:  at TTMp32Gme/TttoolHandler.pm line 267.

Is there any way to reset the settings to how it was the first time I used the software? It did work well, I just need to find a printer that's able to print the codes well enough... 
Thank you for your help!

**Comment by thawn** [comment]
Hi,
the easiest but messiest way to solve this would be to delete the configuration database:
C:\Users\[username]\AppData\Roaming\ttmp32gme\config.sqlite

However, this will **delete all the information about your entire library** but it won't delete the actual files in your library so you can always re-import them from  C:\Users\[username]\AppData\Roaming\ttmp32gme\library

A more clean but less simple way would be to open the config.sqlite file with a sqlite editor. Inside find the table config and change the "value" of the "tt_dpi" parameter.
The SQL syntax would be: UPDATE "config" SET value='1200' WHERE param='tt_dpi';

**Comment by thawn** [comment]
I will change the code for the next release so that the program refuses to set the pixel size to a value that causes tttool to complain.

**Comment by thawn** [comment]
in the latest source code, it is not possible any more to set the pixel size or the resolution to values that make tttool complain and get the user into a situation where he cannot set the pixel size to valid values any more.

**Comment by thawn** [comment]
Please let me know if you still need help fixing your config file and I'll find a solution.
