### ISSUE TITLE
Fehler beim Kopieren der Dateien in das Album

### ISSUE THREAD

**Issue by leppo5940** [thawn/ttmp32gme#3]
Hallo zusammen,
bei mir taucht folgender Fehler beim importieren einer MP3 Datei in die Library auf:

copying albums to library
unhandled callback exception on event (/, AnyEvent::HTTPD=HASH(0x84bc8a0), AnyEv
ent::HTTPD::Request=HASH(0x84c1c80)): Can't call method "get_frame" on an undefi
ned value at TTMp32Gme/LibraryHandler.pm line 212.

Danach erscheint dann auch keine der Dateien in der Library.

Ich habe mitlerweile alle releases und 3 verschiedene Windows Rechner  (Win 7, 10) und unterschiedliche Browser getestet.

**Comment by thawn** [comment]
Hallo,
Danke für den Bug report. Ich brauche aber schon mehr informationen, so dass ich das Problem bei mir reproduzieren kann:
welche Platform (windows/mac/linux)?
hast Du den perl source code ausgeführt oder eine kompilierte Datei (z.B. .exe)
was genau hast Du gemacht bevor der Fehler aufgetreten ist?
gibt es eine Fehlermeldung?

**Comment by leppo5940** [comment]
Na klar brauchst du mehr Infos :-) . Hatte im ersten Post zu früh auf Enter gedrückt....

**Comment by thawn** [comment]
Da kommt das Modul, das die Tag Informationen auslesen soll wohl nicht mit Deinem MP3 file klar.
Evtl. hilft es, wenn Du die MP3 Tag Informationen mit einem Editor wie z.B. http://www.mp3tag.de/ änderst und speicherst (als id3v2).

es wäre super, wenn Du mir eine der mp3 Dateien zum testen zur verfügung stellen könntest, dann kann ich dafür sorgen, dass das Programm sich bei solchen Dateien nicht aufhängt sondern weiter macht.

**Comment by leppo5940** [comment]
Habe gerade mal mit verschiedenen mp3 Dateien ohne Umlaute getestet. (ganz ohne Tag, mit ID3v2.3, ID3v1) überall der gleiche Fehler wie oben.
Interesanterweise tauchen die Dateien unter:
d:\USER\AppData\Roaming\ttmp32gme\library\temp\1
auf

**Comment by thawn** [comment]
einfach per drag und drop in ein comment posten (eine mp3 Datei sollte reichen, maximal 25 MB)

Kannst Du bitte auch noch einmal probieren, ein Bild zusammen mit den mp3 Dateien hochzuladen?

**Comment by leppo5940** [comment]
Sorry , muss meinen obigen Kommentar berichtigen. Hab gestern noch mal alles durchprobiert.
Mit ID 3v2.3 und ID 3v2.4 geht es. 
Der Fehler tritt nur bei Dateien ohne Tag und mit ID3v1 Tags auf.
Wenn der Fehler schon einmal da war, kann man auch keine Dateien mit ID3v2 Tags mehr importieren.
Erst nach einem neustart des Programms gehts wieder.

**Comment by thawn** [comment]
o.k. dann weiss ich wo der Fehler ist. Ich habe den Fehler jetzt im 
Quellcode behoben, der Fix wird also im nächsten Release eingebaut sein.

Vielen Dank für den Bug report und das Testen :)
