### ISSUE TITLE
Ubuntu 18.04 does neither show the tiptoi nor is recognizing configuration settings 

### ISSUE THREAD

**Issue by siyman** [thawn/ttmp32gme#31]
Hi there,
great project overall - thank you very much for your efforts! I tried it some months ago with the installation instructions for linux but have not been very productive since docker on Ubuntu always needs to be root, whereas compiled builds do not work that way.
Today I tried it with the appropriate command from your github page and got ttmp32gme to run. Bad news - the tiptoi pen is not recognized at all, even though I added the necessary information in the commandline pointing to the regarding mount point. Even worse: I cannot receive any kind of gme files. The command line editing does not work, too.
Any experience with this kind of issues or am I on the stranded?
Thanks in advance,
Simon

**Comment by thawn** [comment]
Are you sure about docker on ubuntu? the docker daemon needs to run as root but then you should be able to start containers as a normal user.

**Comment by siyman** [comment]
Thanks for your fast reply and apollogies for the delay.

I tested it on another Ubuntu 18.04 machine where I installed docker from scratch (docker.io from official repositories). First I had to remove apostrophes from the {'USER'} tag in one line off ttmp32gme whereas it is not that way in the other one. Still, I recieve this error message:
"docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=ttmp32gme: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'."
The docker service has been started manually via systemd as sudo to make sure everything is up and running.

Any ideas?
Thanks in advance!

**Comment by thawn** [comment]
According to the [official Docker docs](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user) you need to do the following:

To create the docker group and add your user:
```bash
sudo groupadd docker
sudo usermod -aG docker $USER
```
Log out and log back in so that your group membership is re-evaluated.

**Comment by thawn** [comment]
closed due to inactivity

**Comment by siyman** [comment]
Sorry for the inactivity. Actually I solved it with your help a while back and got everything up and running. My bad, thank you very much! (Sadly my printer is unable to print in an appropriate density/dpi, neither under windows nor ubuntu)
Please mark as solved!

**Comment by thawn** [comment]
I am glad that your software problem was fixed.

Sorry to hear that the printing did not work. I vaguely remember that some people reported success with some online printing services that offer 1200 dpi printing on the [tttool mailing list](https://lists.nomeata.de/archive/tiptoi/)
