### ISSUE TITLE
OSX can't open release "ttmp32gme-0.3.2.dmg"

### ISSUE THREAD

**Issue by masc4ii** [thawn/ttmp32gme#33]
I tried to download and open you latest release on OSX 10.9.5 (ttmp32gme-0.3.2.dmg). Unfortunately it is not possible to open the image.
![Bildschirmfoto 2020-01-15 um 18 37 55](https://user-images.githubusercontent.com/30245296/72457104-28748a80-37c6-11ea-894e-cc0312b1e122.png)
Any idea? Thanks for your help! 

Edit: Tried all releases down to 0.2.3 now, without success.

**Comment by thawn** [comment]
I just downloaded the image to my mac and it worked without issues. 
1) Are you sure that the downloads finished (the files should be ~30 mb)?
2) What version of OS X are you using?
3) How old is your mac? Is it a powerPC or intel mac?

**Comment by thawn** [comment]
I just googled your error message and found this:
https://www.gutefrage.net/frage/mac-os-x-1092-diskimagemounter-error-keine-aktivierbaren-dateisysteme

> Ein User schreibt, dass MacFuse und NTFS-3G die Ursache waren. De- und dann wieder installiert, und der Fehler war weg.


> Ein anderer: "Extrem bekloppt, hat aber funktioniert: rechte Maustaste, "Öffnen mit" und das Mount Tool auswählen. Ich bin mir nicht sicher, warum das nicht standardmäßig verknüpft war und keine Ahnung mit welcher Software er versucht hat die .dmg sonst zu öffnen - aber - es funktioniert"


Since the error occurs with all images - which I know to work on many different machines - I am assuming the problem is with your system.

**Comment by masc4ii** [comment]
1. Download is finished, yes
2. It is a MacBookPro 2010 13.3" (Intel Core2Duo) with Mavericks 10.9.5

I'll see this evening, if MacFuse could be the problem. But if I understand right, I should not be able to open any dmg. But I can open other dmg's without any problem.

**Comment by thawn** [comment]
dmg files can contain images in different formats. I am using compressed images. Maybe the problem is that your OS cannot handle them? 10.9 is quite old...

**Comment by masc4ii** [comment]
I now tried uninstalling FUSE. Still can't open your dmg. But when reinstalling FUSE, its dmg opened without any problem.

Opening with right click and manually selecting DiskImageMounter also did not change anything. 

No idea, how I can help to find out this problem. I nearly daily create and open dmg's and have never seen such an issue.

I now tried another Mac (OSX 10.13), and this one could open the image. But unfortunatelly the app just brings errors. I zipped the app and tried to run it on my older MacBook on 10.9.5, and the errors are identical.
![Bildschirmfoto 2020-01-16 um 17 49 56](https://user-images.githubusercontent.com/30245296/72545014-a0a38480-3888-11ea-9a94-99006d6495ba.png)

**Comment by masc4ii** [comment]
I tried to open the image with the terminal. This is what the terminal tells:

```
hdiutil attach -verbose ttmp32gme-0.3.2.dmg 
Initialisieren …
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CMacBinaryEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CAppleSingleEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CEncryptedEncoding
DIFileEncodingInstantiatorProbe: interface  0, score      900, CUDIFEncoding
DIFileEncodingNewWithBackingStore: CUDIFEncoding
DIFileEncodingNewWithBackingStore: instantiator returned 0
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CSegmentedNDIFEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CSegmentedUDIFEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CSegmentedUDIFRawEncoding
DIDiskImageInstantiatorProbe: interface  0, score     1000, CUDIFDiskImage
DIDiskImageInstantiatorProbe: interface  1, score        0, CSparseBundleDiskImage
DIDiskImageInstantiatorProbe: interface  2, score        0, CSparseDiskImage
CRawDiskImage: data fork length 0x0000000001C3D4A7 (29611175) not a multiple of 512.
DIDiskImageInstantiatorProbe: interface  3, score     -100, CRawDiskImage
DIDiskImageInstantiatorProbe: interface  4, score        0, CDARTDiskImage
DIDiskImageInstantiatorProbe: interface  5, score        0, CDiskCopy42DiskImage
DIDiskImageInstantiatorProbe: interface  6, score    -1000, CNDIFDiskImage
DIDiskImageInstantiatorProbe: interface  8, score     -100, CShadowedDiskImage
DIDiskImageInstantiatorProbe: interface  9, score    -1000, CCFPlugInDiskImage
DIDiskImageInstantiatorProbe: interface 10, score     -100, CWrappedDiskImage
DIDiskImageNewWithBackingStore: CUDIFDiskImage
DIDiskImageNewWithBackingStore: instantiator returned 0
Überprüfen …
Überprüfung beendet …
Error 0 (Unbekannter Fehler: 0).
Die erwartete CRC32-Prüfsumme ist $B9E6923F
Aktivieren …
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000005 seconds
2020-01-16 20:17:39.605 diskimages-helper[1412:4513] DIHelperHDID serveImage: attaching drive
{
    autodiskmount = 1;
    "hdiagent-drive-identifier" = "A9762D8B-5D5F-4A2D-867B-7AE94D6E7EFD";
    "unmount-timeout" = 0;
}
2020-01-16 20:17:39.608 diskimages-helper[1412:4513] DIHelperHDID serveImage: connecting to myDrive 0x4E0B
2020-01-16 20:17:39.608 diskimages-helper[1412:4513] DIHelperHDID serveImage: register _readBuffer 0x10474d000
2020-01-16 20:17:39.608 diskimages-helper[1412:4513] DIHelperHDID serveImage: activating drive port 19467
2020-01-16 20:17:39.609 diskimages-helper[1412:4513] DIHelperHDID serveImage: set cache enabled=TRUE returned SUCCESS.
2020-01-16 20:17:39.609 diskimages-helper[1412:4513] DIHelperHDID serveImage: set on IO thread=TRUE returned SUCCESS.
Volume-Überprüfung ist abgeschlossen …
Aktivieren …
2020-01-16 20:17:39.626 diskimages-helper[1412:2a03] -remountReturningDictionary: detaching because no mountable filesystems.
Aktivieren …
Error 112 (Keine aktivierbaren Dateisysteme).
Fertigstellen …
DIHLDiskImageAttach() returned 112
hdiutil: attach failed - Keine aktivierbaren Dateisysteme
```

**Comment by masc4ii** [comment]
I think I found it: https://deciphertools.com/blog/2017-10-02-no-mountable-file-systems/
See point 4. Did you use Apple-APFS file format? Then your dmg image won't open on older OSX than 10.12. If you use e.g. Apple-HFS, it would run also on older Macs like mine. 

So now, I still have the other problem with the app itself. Is there a library missing? Shouldn't be the libraries deployed to the app? If I watch into the app package, there is no lib at all included... is that correct? The apps I compile have lots of libs and frameworks in there...

**Comment by thawn** [comment]
yes it is correct that there is just one executable. This is created with perl pp and it is essentially an archive containing a perl runtime, the code and the required libraries.
So far I didn't include libxml2 because the version included with macOS should be compatible. However, it could be that I changed the version of libxml on my machine. Unfortunately, I don't have a vanilla mac to test this. Could you please test this file: https://thawn.noip.me/owncloud/index.php/s/gzLLrjjGk3e5HLq

**Comment by thawn** [comment]
btw: thank you very much for your help with debugging this. I am sure that the others who suffer from the problem and don't know how to help will profit greatly :)

**Comment by masc4ii** [comment]
Your welcome. Thanks for all your work and help! 😄 
I tried it, but the problem is still there. Here is what the app tells on HighSierra 10.13.6:
![Bildschirmfoto 2020-01-17 um 11 40 13](https://user-images.githubusercontent.com/30245296/72606028-232a5380-391e-11ea-886e-8854490e71f7.png)
Nearly all my Macs aren't vanilla too, but from what I've seen in the past: if all used libraries are contained and linked in the app package (full deployment), it ran very well everywhere... But I never tried perl, I mostly use Qt for that.

**Comment by thawn** [comment]
O.k. it was worth a try. I'll set up a Mac os vm and try to get it to work in there. I'll get back to you once I get it working in the vm.

**Comment by masc4ii** [comment]
Wow, thanks. Please let me know, if I can help somehow, e.g. with testing.

**Comment by thawn** [comment]
Could you please try [this file](https://thawn.noip.me/owncloud/index.php/s/BZDH8s6DQkNmq6g)

**Comment by thawn** [comment]
also, could you please try if you can open [this dmg image file](https://thawn.noip.me/owncloud/index.php/s/Q379jNQYJQ9xi8e) with your old mac OS version?

**Comment by masc4ii** [comment]
Nice! Thumbs up! The executable works and I can get the browser page. The message in the application is:
![Bildschirmfoto 2020-01-20 um 19 32 44](https://user-images.githubusercontent.com/30245296/72749956-c77cf600-3bbb-11ea-8f10-cbc193b4a1f1.png)

The image also opens! Yay. Thank you so much! Now I "just" have to find a printer which prints these patterns... the first 4 printers with many many settings did not work... but I think this is my problem now 😄 (I tried the Ravensburg sample).

**Comment by thawn** [comment]
Great, thanks a lot for your help! :-)
