### ISSUE TITLE
Error adding Album to Library

### ISSUE THREAD

**Issue by sladdythebrain** [thawn/ttmp32gme#34]
Hello,

I try to create a new audibook but after click the "Add Album to Library" it will fail with this error:

[MSG] using tttool: C:\Users\ANDREA~1.SCH\AppData\Local\Temp\par-616e64726561732e7363686c6567656c\cache-d4cd2848b70ff6e5ca5e050927fb42b31959a03d\inc\lib\tttool.exe
copying albums to library
unhandled callback exception on event (/, AnyEvent::HTTPD=HASH(0x913c350), AnyEvent::HTTPD::Request=HASH(0x4017c40)): Can't call method "basename" on an undefined value at TTMp32Gme/Build/FileHandler.pm line 102.

Any idea how to fix this kind of Problem?

Thanks

**Comment by thawn** [comment]
This may be a filename issue. Try to rename the files so that they don't contain any spaces or special characters. Also, make sure that there are no hidden files (like thumbs.db) or any other non- audio or image files in the album.

Let me know if this helps :)

**Comment by thawn** [comment]
if renaming the files or removing some files helps, it would be great if you could post the problematic file names so that I can reproduce the issue and make the software more robust in the future.
Cheers :)

**Comment by sladdythebrain** [comment]
Hello, I just changed the path for the library from my profile to c:\temp and the all start working. :-) Not need to rename the files...

Thanks for your help.
