### ISSUE TITLE
Change the size of the OIDs 

### ISSUE THREAD

**Issue by Dani22m** [thawn/ttmp32gme#47]
Is there any way to change the size of  the oids on the printout ?

If the tile is very small, the oids destroy the layout 

![image](https://user-images.githubusercontent.com/31921248/130149636-99c59730-fb29-4daa-ac80-d9490ea15535.png)

**Comment by thawn** [comment]
I tested smaller OIDs and they are not reliably recognized by the TipToi pen. I recommend scaling up the cover image in a graphics program.
-------- Ursprüngliche Nachricht --------Von: Dani22m ***@***.***> Datum: 19.08.21  23:57  (GMT+01:00) An: thawn/ttmp32gme ***@***.***> Cc: Subscribed ***@***.***> Betreff: [thawn/ttmp32gme] Change the size of the OIDs  (#47) 
Is there any way to change the size of  the oids on the printout ?
If the tile is very small, the oids destroy the layout
