### ISSUE TITLE
Impossible to edit OID number of an album

### ISSUE THREAD

**Issue by alex-bagnoud** [thawn/ttmp32gme#48]
Hi,

First, thanks a lot for this awsome tool, it is very useful and I have a lot of fun developing new project for kids with it.

I noticed that I get an error when I try to set the OID number of an album. After changing it, I get a "connection error" when I update the album. 

I needto change theOID number because my other computer crashed, and I lost all the ttmp32gme library. Now, I am restarting a new one, and I want to avoid OID conflicts with the files that where generated on the first (and lost) library.

Thanks in advance for your help!

Best regards,

Alex

**Comment by thawn** [comment]
I am able to reproduce the issue. I will try to fix it in the next release.

**Comment by thawn** [comment]
fixed in latest development version

**Comment by thawn** [comment]
fixed in v1.0.1
