### ISSUE TITLE
FRENCH: The tiptoi pen does not recognize the GME file

### ISSUE THREAD

**Issue by severin-lemaignan** [thawn/ttmp32gme#5]
I've assembled a first album into a GME file, copied the GME file to the pen, and printed the control sheet.

The pen recognizes the pattern on the control sheet, however, it tells the audio files are not available.

As I've read on the `tttool` issue tracker that it might be necessary to set the language tag to the one of the pen, I've re-assembled a GME file with the language tag set to our pen (FRENCH). It does not however work any better.

Any ideas how I could debug that?

**Comment by thawn** [comment]
Sorry, I don't have any experiences with pens in other languages than 
german and I don't have a french pen to test.

It seems you have already found ttmp32gme's library location where the 
yaml and audio files are located so that you can use tttool manually. 
Beyond that, I cannot provide any help. Please try the tttool mailing list:

https://lists.nomeata.de/mailman/listinfo/tiptoi

they have been discussing languages and will be happy about feedback and 
may be able to help you.

If you find a solution, please let me know so that I can add language 
support to ttmp32gme.

Best

Till

**Comment by thawn** [comment]
There is one other thing you could try:

when you switched on the pen for the first time after you copy the gme 
file to the pen, the pen should tell you to wait a moment. If that does 
not happen, you can try the following: Attach the pen to your computer 
and mount it. Do NOT write any data to the pen and disconnect it WITHOUT 
unmounting. This will trigger the pen to do a filesystem scan and scan 
for new gme files.

I hope that helps.

**Comment by creativecat** [comment]
I have a similar problem, but with a german pen. I run the ttmp32gme on a Mac. The selected files were successfully added to the pen (I can see the gme file on the pen over the finder).
Printing also runs successfully but the pen doesn't recognize the gme file. I tried different settings for the ink-printer itself (best quality, standard...) and in the browser (resolution etc.)...

In the console I get the following errors (from starting the program until printing):
```
[MSG] Server running on port: 10020
Open http://127.0.0.1:10020/ in your favorite web browser to continue.

[MSG] using tttool: /var/folders/d8/l2j8p0qs3m372xw63kmvfz5m0000gs/T/par-486f6d656f72646e6572/cache-ba514ff236fd8dd6d248830a52e34eeda8ef9648/inc/lib/tttool
Can't exec "/var/folders/d8/l2j8p0qs3m372xw63kmvfz5m0000gs/T/par-486f6d656f72646e6572/cache-ba514ff236fd8dd6d248830a52e34eeda8ef9648/inc/lib/wkhtmltopdf": No such file or directory at TTMp32Gme/PrintHandler.pm line 169.
Use of uninitialized value $wkhtmltopdf_version in pattern match (m//) at TTMp32Gme/PrintHandler.pm line 170.
```

**Comment by mirkowein** [comment]
I've same issues as creativecat.
Neither the old tiptoi nor the new one recognize any of my printed controls. same errors in console, but i don's think the problem has anything to do with the recognition. (only print Page in browser?)
Any suggestions? I've printed with ink and laser.
many thanks!

**Comment by thawn** [comment]
@creativecat , @mirkowein 
Thank you for your bug reports.
Your issues are unrelated to this issue. This issue is specific to problems with the french language and have nothing to do with the pen not recognizing printed pages. I have opened a new issue for your problems here: #11 

Please read the pages I have linked in there, they give good advice on getting your printer to work with tttool (which is what ttmp32gme uses to create the oid codes for the print pages).

**Comment by thawn** [comment]
I am closing this issue as an upstream problem of tttool. Please feel free to reopen it if you manage to create FRENCH language gme files with tttool but not with ttmp32gme.

**Comment by rafiberlin** [comment]
> I am closing this issue as an upstream problem of tttool. Please feel free to reopen it if you manage to create FRENCH language gme files with tttool but not with ttmp32gme.
Hi @thawn,

I have been able to make a slight tweak to make it work with a French firmware.

In src\TTMp32Gme\TttoolHandler.pm

I added these two lines (in italic):

sub make_gme {
my ( $oid, $config, $dbh ) = @_;
my $album = get_album( $oid, $dbh );
$album->{'old_oid'} = $oid;
my $yaml_file = file( $album->{'path'},
 sprintf( '%s.yaml', cleanup_filename( $album->{'album_title'} ) ) );
my $fh = $yaml_file->openw();
print $fh "#this file was generated automatically by ttmp32gme\n";
print $fh "product-id: $oid\n";
**### print $fh "gme-lang: FRENCH\n";
print $fh "comment: CHOMPTECH DATA FORMAT CopyRight 2009 Ver2.4.0316\n";**
close($fh);

I would be a great enhancement to have the possibility to configure gme-lang and comment for the GME file; I assume this would be helpful for any other firmware (ITALIAN, ENGLISH, RUSSIAN...)

**Comment by thawn** [comment]
@rafiberlin thanks a lot for reporting the fix. I will implement a language selection option in the next release.

**Comment by thawn** [comment]
In Version 0.2.3 gibt es jetzt die Möglichkeit, in der Konfiguration die Sprache auszuwählen. Könnte bitte jemand mit einem anderssprachigen Stift testen ob das funktioniert? Danke!

**Comment by thawn** [comment]
I am making this issue as stale. Unless I hear back from someone who still has problems with different languages within 30 days,  I am assuming the problem is fixed and closing this issue.

**Comment by thawn** [comment]
Please re-open the issue if you still have problems
