### ISSUE TITLE
Using saved PDF on display

### ISSUE THREAD

**Issue by Mahelita** [thawn/ttmp32gme#50]
I just tried using a PDF saved from the printing with a tiptoi.
The tiptoi does not seem to detect the OIDs when pointing at the screen.
What resolution would a display need to have to make this possible?
Could changing the pixel size of OIDs or the OID DPI in the print general options help with lower resolution displays?
Thanks!

**Comment by thawn** [comment]
I doubt this will work on any display. Displays are built from pixels which means that even a completely white background is not uniform if you look at it under a magnifying glass (which is essentially what the tiptoi pen does). This will confuse the algorithm that tries to read the OID codes, even if the resolution of the screen is high enough (>600 dpi).
