### ISSUE TITLE
freezing after adding the 5th album to library

### ISSUE THREAD

**Issue by antilles345** [thawn/ttmp32gme#52]
Hello,

Using WIN10 executable 1.0.0.
Fresh install (deleted Library, EXE, tttool folder)

I'm trying to create a small book with a couple of albums (single mp3 file each, all upload and convert fine individually) for my son to have his audiobooks with him. (Total Filesize is 703MB, largest file/album is 27.5MB)

Once I upload a 6th album to the library, I cannot do anything anymore in ttmp32gme. No uploads, no conversions, no edits.
There is no output in the console from this point onwards, the commands don't seem to transferred from the web interface at all.

**Comment by antilles345** [comment]
Just adding that I tried clearing the library of mp3 files but the issue persists

**Comment by thawn** [comment]
Thank you very much for your bug report.

I have a few questions:

Is it always the same album that fails? If yes, please tell me the exact file name and the exact content of the metadata - or even better, send me the file in question.

What if you change the order in which you upload the albums - is it always the 6th album that fails?

**Comment by antilles345** [comment]
Thanks for your reply.

to answer your questions: I have tried different albums/files It is always the 6th that fails. I have made sure, that the metadata and filenames don't contain any weird characters. I have checked for it the id3 tags to be id3v2.

I will send you a batch of files via pm? Each of those should be an individual album.

**Comment by thawn** [comment]
you can upload the files here:
https://thawn.noip.me/owncloud/index.php/s/GY6rgRARkNaeMGR

I will try to reproduce the issue on my test system and get back to you.

Cheers

**Comment by antilles345** [comment]
I didn't have rights to upload, but I think I solved it. At least it's working today.

It appears, that even in the fielnames and the ID3 tags not used there are unallowable characters. After deleting all unused tags and making sure all characters are ascii base set only, it is working. I got up to 12 albums during testing without issue.

**Comment by thawn** [comment]
good to know :) Could you please let me know what non-ascii characters were in the file names?
Also, could you please tell me the windows codepage setting on your machine?
I would like to try and fix the character encoding issues in the next version.

**Comment by thawn** [comment]
I have now changed the access rights in the owncloud and uploading should work.
https://thawn.noip.me/owncloud/index.php/s/GY6rgRARkNaeMGR

**Comment by vschi** [comment]
I have somehow the same issue like indicated in this bug report.
Windows 10
Fresh install (deleted Library, EXE, tttool folder)


I'm adding 5 episodes (5 mp3 files) from the same album without any issues.
The print command is working after each episode upload.
By adding the 6th album the systems quits the connection. Not possible anymore to print, delete or update.
It just circles in the browser seems to wait for response.

I had originally Umlaute in the file name in all album names but the problem persists even after removing those.
Tried uploading without any ID3 tags and no Umlaute in the file name but it continues to fail.


Tried to debug it down to somethin specific but I'm failing to find something specific that causes the issue.
For example it is possible to upload all mp3 in just one album and print it. No issues with that.

Beside that album everything is working fine and I was able to create a lot of working albums but this one is the only one problematic.

I'm happy to share my files with you to replicate the issue.
The upload link above is not working anymore :(

**Comment by vschi** [comment]
I did now the following test:
Uploading 6 completely different albums. One after the other without waiting.
Now the browser indicates a loading or waiting some some kind of action from your application.
While waiting it is not possible to edit anything, everything fails.

So the problems seems to be related to the upload processing.
All files are copied properly to their library location. Also the SQL Lite DB includes them.

The console shows the following:

Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at Music/Tag.pm line 1066, <DATA> line 1.
[MSG] Server running on port: 10020
Open http://127.0.0.1:10020/ in your favorite web browser to continue.

[MSG] using tttool: C:\Users\xx\AppData\Local\Temp\par-56696b\cache-79be178b2945f1b0b8b1dcc94b3b41a083d99cb8\inc\lib\tttool.exe
copying albums to library
deleting C:\Users\xx\AppData\Roaming\ttmp32gme\library\temp
copying albums to library
deleting C:\Users\xx\AppData\Roaming\ttmp32gme\library\temp
copying albums to library
deleting C:\Users\xx\AppData\Roaming\ttmp32gme\library\temp
copying albums to library
deleting C:\Users\xx\AppData\Roaming\ttmp32gme\library\temp
copying albums to library
deleting C:\Users\xx\AppData\Roaming\ttmp32gme\library\temp
copying albums to library
deleting C:\Users\xx\AppData\Roaming\ttmp32gme\library\temp


**Is there any kind of way to start the windows application in a debug mode and see more details on what is happening behind the scenes?**

**Comment by vschi** [comment]
**I think I found the problem:**
It seems like the application awaits via JQuery an cover image for each album.

As the difference from before used albums was the not existing album cover image in the mp3 files I have added the cover image right after the uploading process.
Then I have uploaded the next album and continued right away with the next cover.
5 albums later I was able without any issues to create my printouts.

I experienced anyhow some failures to edit the image as it wasn't uploading.
But after restarting the application and then uploading the cover again I was able to successfully finish.

Maybe there is a dependency to load the cover images on every loading of the library. If one or two covers are not existing jquery is still working. But if 6 cover images are missing it is not able to overcome that waiting status and the whole application stops working.

**Comment by thawn** [comment]
@vschi thank you very much for the detailed information and investing so much effort towards tracking down the problem.

**Comment by thawn** [comment]
Which browser (version) are you using for your tests? If the problem is with java script, then the browser (or a plugin) could be involved.

**Comment by thawn** [comment]
In my tests, I usually upload one cover image together with the mp3 files. In that case the software uses the uploaded image (and ignores images embedded in the mp3 files).

I am not sure that I fully understand your workflow.

Are you uploading the mp3 files with embedded cover art?

Or are you first uploading the mp3 files and then editing the albums to add the cover art?

Could you please try to describe step by step what you are doing and at which point the problem occurs?

Cheers,

Thawn

**Comment by vschi** [comment]
Using latest Chrome on Win10.

I'm uploading mp3 files without any cover embedded.
First uploading the mp3 files than editing the newly created album and adding a cover to it. 
This works.

I had worked with several albums before where the covers where embedded, and had no issues.


But if you don't update the cover images right after upload it starts to be problematic after the 4 th album. 
With the 6 th album there is no update possible anymore.


1. Upload a album without cover embedded
2. Continue for the next 5 albums
3. Then open the library and try to edit the album (name or cover) and the sync will fail. Also not possible anymore to add an cover.

**Comment by vschi** [comment]
This is how it looks in the inspect > network after the first album is uploaded:
![image](https://user-images.githubusercontent.com/24713300/160093648-7afe038a-361f-4d2f-bfda-4c88964c19e6.png)

After next album:
![image](https://user-images.githubusercontent.com/24713300/160094099-146e56d0-0179-4e45-980d-ee06a7ba2f3c.png)

And thats it. It is stuck already after two albums.

**Comment by thawn** [comment]
Thank you very much for the detailed info. This should help me reproduce the issue.
To be honest, I never tried uploading several albums without cover image. In my tests, I have one test that uploads one album without cover and that works fine (As you know ;-) )

As a workaround, I suggest to drag the entire folder containing the mp3 files and a cover image (jpg) to the uploader. That is less cumbersome than editing each album after upload.

**Comment by thawn** [comment]
should be fixed in v1.0.1
