### ISSUE TITLE
Debugging Mode with all / more details

### ISSUE THREAD

**Issue by vschi** [thawn/ttmp32gme#54]
While debugging another issue of your application I wanted to raise 2 feature request.

1. The application had in version 0.3.4 more detailed logs presented in the console. I expect this happens because of debug=2 that was set. This is not possible anymore in version 1.0.0 as debug has a value of 0 or 1. It would be great to see more details in the console by using debug = 2 and uncomment all existing debug outputs in the code.
2. There is no debug for the update of data in the sqlite. For example if a value is updated in the frontend for an album. Something happens in the backend but no output in the debug.

**Comment by thawn** [comment]
Thank you very much for your feature request. I think these are very good suggestions. I suggest to (re) implement a way to enable debugging via command line arguments. E.g. ttmp32gme -debug=2

Also the debugging for database requests is a good idea.

Unfortunately, I cannot make any promises as to when I will have time to work on this. If you need this urgently, and have the time, feel free to take a shot at this yourself - merge requests are always welcome ;-)

Cheers,

Thawn

**Comment by vschi** [comment]
I guess if somebody needs debug data, than he needs as much as possible :)
So ttmp32gme -debug should use debug=2 and not differentiate between those debug modes.

More "urgent", if we can talk about urgent for a tiptoi soundplayer is the issue #52 with the cover missing problem.

**Comment by thawn** [comment]
Actually, when I tried to debug myself, at some point, it was difficult to sift through all the data. Therefore, I started using different debug levels. This is a well known approach used for logging. Apparently, the -debug flag still works. did you try if -debug=2 gives you more extensive debug messages?

**Comment by vschi** [comment]
-debug=2 is not working as the debug parameter is not accepting values.

**Comment by thawn** [comment]
o.k. thanks, I will try to implement that.

**Comment by thawn** [comment]
In the latest development version, you can now set the debug level via the command line argument -d=3 or -debug=3

**Comment by thawn** [comment]
the command line parameter -d=3 should work in v1.0.1
