### ISSUE TITLE
Start from higher OID

### ISSUE THREAD

**Issue by vschi** [thawn/ttmp32gme#55]
Sorry to open an issue for this question:

Lets assume I have already uploaded 20 albums and printed the covers. 
Everything is fine.
I expect every OID needs to be unique. Meaning if I have already a OID used on the tiptoi device with the number 920 than I should not use that number again.

Now I'm deleting the library in your application and starting from scratch.
All old OID's are not present in the library anymore.

If I upload a new album it uses the same OID 920 for the first album.
But it is already used from one of the first 20 albums.
I expect this will cause problems on the device as the OID is not unique anymore.

How can I tell your application to start with OID 981 for the next album.
Changing of the OID in the album causes a error message. 
It seems like the existing OID values can't be changed in the library view (while they are editable form fields).
After updating the album with a new OID it shows the following error:
![image](https://user-images.githubusercontent.com/24713300/160097646-58b692a8-c3a8-4031-a7a9-02851edb5bac.png)

**Comment by thawn** [comment]
Thank you very much for reporting this issue.

The problem with editing OIDs is a known bug (issue #48). Please post further inqueries about that bug there.

A separate issue is your request to be able to start with a different OID. This not so easy to implement and could potentially cause problems with official Ravensburger books. Therefore, I am reluctant to implement this feature.
As a workaround, you could upload the same number of dummy albums (with very small files) that you had in the library before you deleted it. Then, new albums will have different OIDs than the old ones.

**Comment by thawn** [comment]
in v1.0.1 it is now possible to manually change OIDs
