### ISSUE TITLE
Kopieren auf Stick funktioniert nicht

### ISSUE THREAD

**Issue by SebastianBl** [thawn/ttmp32gme#6]
Hallo und vielen Dank für dieses Projekt.

Installation, Umwandlung und auch das Editieren von Einträgen klappt alles super. Nur das Übertragen der Dateien klappt leider nicht.

Folgende Meldung erscheint in der Konsole:
`
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at Music/
Tag.pm line 1066.
[MSG] Server running on port: 10020
Open http://127.0.0.1:10020/ in your favorite web browser to continue.

[MSG] using tttool: C:\Users\brainml\AppData\Local\Temp\par-627261696e6d6c\cache
-8f1304b3f7e188adb49363ef0e48ad20dae87431\inc\lib\tttool.exe
C:\Users\brainml\AppData\Local\Temp\par-627261696e6d6c\cache-8f1304b3f7e188adb49
363ef0e48ad20dae87431\inc\lib\tttool.exe --dpi 1200 --pixel-size 2 assemble 07_-
_Piraten.yaml
[ERROR] AesonException "when expecting a [a], encountered Null instead"

[MSG] Copying  to F:\
unhandled callback exception on event (/library, AnyEvent::HTTPD=HASH(0x80a9698)
, AnyEvent::HTTPD::Request=HASH(0x80c9238)): Can't copy to file F:\: it is a dir
ectory at TTMp32Gme/TttoolHandler.pm line 300.`

Wäre klasse, wenn es eine Idee gibt woran es liegt.

(Windows 7, Chrome, TipToi PLayer Stift neuste Version (2Tage alt))

Grüße
Sebastian

**Comment by thawn** [comment]
Hallo Sebastian,

Es gab einen Fehler beim Erstellen der gme Datei. ttmp32gme unterstützt 
nur 64 bit Betriebssysteme. Falls Du ein 32 bit Windows hast, liegt es 
daran. Falls nicht, könntest Du bitte den Inhalt der Datei 07_-
_Piraten.yaml posten? Der Pfad wo die Datei liegt wird in der ttmp32gme 
Bibliothek angezeigt.

Gruss

Till

**Comment by SebastianBl** [comment]
HI und danke für die Antwort,
ich habe ein 64bit System, daran sollte es also nicht liegen.

Die Datei hat folgenden Inhalt:
`#this file was generated automatically by ttmp32gme
product-id: 923
media-path: audio/track_%s
init: $current:=0
welcome: 
scripts:
  play:
  next:
  prev:
  stop:
  - C C
  t0:
  - $current:=-1 P(-1) C
  t1:
  - $current:=-1 P(-1) C
  t2:
  - $current:=-1 P(-1) C
  t3:
  - $current:=-1 P(-1) C
  t4:
  - $current:=-1 P(-1) C
  t5:
  - $current:=-1 P(-1) C
  t6:
  - $current:=-1 P(-1) C
  t7:
  - $current:=-1 P(-1) C
  t8:
  - $current:=-1 P(-1) C
  t9:
  - $current:=-1 P(-1) C
  t10:
  - $current:=-1 P(-1) C
  t11:
  - $current:=-1 P(-1) C
  t12:
  - $current:=-1 P(-1) C
  t13:
  - $current:=-1 P(-1) C
  t14:
  - $current:=-1 P(-1) C
  t15:
  - $current:=-1 P(-1) C
  t16:
  - $current:=-1 P(-1) C
  t17:
  - $current:=-1 P(-1) C
  t18:
  - $current:=-1 P(-1) C
  t19:
  - $current:=-1 P(-1) C
  t20:
  - $current:=-1 P(-1) C
  t21:
  - $current:=-1 P(-1) C
  t22:
  - $current:=-1 P(-1) C
  t23:
  - $current:=-1 P(-1) C
`

Darüber hinaus liegen folgende Datein in dem Ordner
` Datentr„ger in Laufwerk C: ist Win7


 Verzeichnis von C:\Users\brainml\AppData\Roaming\ttmp32gme\library\07_Piraten

16.02.2017  15:14    <DIR>          .
16.02.2017  15:14    <DIR>          ..
15.02.2017  20:59               835 07_Piraten.codes.yaml
15.02.2017  16:30        78.779.482 07_Piraten.gme
15.02.2017  20:59               989 07_Piraten.yaml
15.02.2017  16:25        78.770.321 Piraten_1.mp3
15.02.2017  16:32            25.568 piraten-40072_01_m.jpg
               5 Datei(en),    157.577.195 Bytes
               2 Verzeichnis(se), 18.764.341.248 Bytes frei
`
Könnte ich die .gme Datei einfach auf den Stick kopieren und schauen ob diese läuft? Dann könnten wir zumindest ausschließen ob die Datei kaputt ist.

Freundliche Grüße
Sebastian

**Comment by thawn** [comment]
Ja, versuche mal, ob die Datei funktioniert. Das Programm macht auch nichts anderes, als die Datei auf den Stift zu kopieren.

**Comment by thawn** [comment]
Falls es nicht klappt, kannst Du mir bitte einen Screenshot von dem Album (vorher bitte auf edit klicken) schicken?

**Comment by SebastianBl** [comment]
Hi,
ich konnte die .gme ganz normal in den root Ordner von dem Stick kopieren. Konnte es aber nicht starten, ich habe aber leider gerade keinen guten Drucker zur Hand. Den Ausdruck zum Starten über den Stick könnte ich erst morgen machen.

In dem "stories" Ordner sind nur die beiden .rav Dateien, da sollte es nicht rein, oder?

Hier noch der Inhalt des Albums, ist kein Screenshot aber alles was dort steht per copy/paste

Das GME Feld ist leer, ist das normal?

`OID: 
923
Album title: 
07 - Piraten
Album artist: 
Die drei ??? Kids
Album year: 
2017
GME file: 
Path: 
C:\Users\brainml\AppData\Roaming\ttmp32gme\library\07_Piraten`

**Comment by SebastianBl** [comment]
Moin Till,

ich habe gerade noch einmal den Ausdruck in guter Qualität erstellt und das .gme File in das Stift root kopiert. Dann funktioniert es!

Die Auswähl Taste (Also der Kreis mit dem Strick links oben), Start und Stop funktionieren. Die vor und zurück Tasten nicht, da das Album nur eine Datei hat.

Es scheint also nur das kopieren der .gme Files nicht zu funktionieren.

Grüße
Sebastian

**Comment by thawn** [comment]
On 16.02.2017 20:15, SebastianBl wrote:
>
> Hi,
> ich konnte die .gme ganz normal in den root Ordner von dem Stick 
> kopieren. Konnte es aber nicht starten, ich habe aber leider gerade 
> keinen guten Drucker zur Hand. Den Ausdruck zum Starten über den Stick 
> könnte ich erst morgen machen.
>
> In dem "stories" Ordner sind nur die beiden .rav Dateien, da sollte es 
> nicht rein, oder?
>
nein, der root ordner ist der richtige Ort
>
> Hier noch der Inhalt des Albums, ist kein Screenshot aber alles was 
> dort steht per copy/paste
>
> Das GME Feld ist leer, ist das normal?
>
nein.
>
> |OID: 923 Album title: 07 - Piraten Album artist: Die drei ??? Kids 
> Album year: 2017 GME file: Path: 
> C:\Users\brainml\AppData\Roaming\ttmp32gme\library\07_Piraten|
>
|Da fehlt der Eintrag des tracks. Ich vermute, dass da irgend etwas mit 
den Metadaten im Id3 Tag komisch ist. Ich schaue mir das nochmal an.|

**Comment by thawn** [comment]
Moin Sebastian,

Das kopieren der GME Datei funktioniert normalerweise schon. Bei Dir ist 
aber beim Erstellen der GME Datei ein fehler aufgetreten, daher fehlt 
der Pfad zur GME Datei in der Bibliothek ohne den kann er aber die Datei 
nicht kopieren. Ich vermute, das hat etwas mit dem Id3 Tag (oder seinem 
nicht vorhandensein) zu tun.

LG

Till

**Comment by SebastianBl** [comment]
Moin,

das war es :-)

Ich habe die Id3 Tags geändert und den fehlenden Eintrag bei "Tracks" auf 1 gesetzt. (Mit dem Freeware Tool mp3tag, klappt sehr gut)

Nun wird sowohl in der Trackliste etwas angezeigt und auch das "copy GME to Stick" funktioniert.
Bei GME steht nun auch etwas. Das Cover, was in den Mp3Tags eigentlich auch drin ist, wird aber nicht übernommen.

Ich werde das nun noch bei weiteren Dateien testen und die verschiedenen kopier Möglichkeiten deines Programmes testen.

Vielen Dank für deine Mühe!
Grüße
Sebastian

**Comment by thawn** [comment]
Hi Sebastian, danke fürs Testen! Ich lasse das issue noch offen. Du hast zwar einen Workaround gefunden, ich möchte aber erst das darunter liegende Problem beheben, bevor ich das issue schließe.

**Comment by thawn** [comment]
fixed in source code
