### ISSUE TITLE
Wishes - Wimmelbook or hidden object book

### ISSUE THREAD

**Issue by tomlieber** [thawn/ttmp32gme#7]
Hi 
I like that interface.. works very well in my case.

But.. Is it easly possbile to change the print design.. 
Like A4 Landscape with a Matrix Layout. i wanna make a wimmelbook.. (or hidden object book) .. in each square is a uploaded Picture and an OID number picture overlay (div transparency? i dont no exactly).  css_image_transparency maybe.. 

Thx a lot ..

**Comment by thawn** [comment]
Hi Tom,

I will not be able to make custom layouts for individual requests (I do have a day job ;-) ).

It sounds to me like what you want is much better done manually with tttool:
http://tttool.entropia.de/

Also, consider to print in two steps: first the images and then in a second step print the oid codes on the same sheet of paper. that way you don't need to worry about transparency and the oid codes often come out better that way.

If you want to customise the layout of ttmp32gme, you will have to change the source code yourself. Best would be to fork the code on Github which would keep the option open to merge your changes back into the main code later.

As a hack you could try to edit the html of the print page using the developer tools of the browser before you print. This will only work with the Edge browser under Windows 10 (no chance on older Windows versions), under Mac and Linux, you can try Chrome or Firefox.

Cheers

Till
